`ifndef GPIO_VH
`define GPIO_VH
`define GPIO_DIRECTION_DIR_BIT_WIDTH 32
`define GPIO_DIRECTION_DIR_BIT_MASK 32'hffffffff
`define GPIO_DIRECTION_DIR_BIT_OFFSET 0
`define GPIO_DIRECTION_BYTE_WIDTH 4
`define GPIO_DIRECTION_BYTE_SIZE 4
`define GPIO_DIRECTION_BYTE_OFFSET 4'h0
`define GPIO_DATA_OUT_VALUE_BIT_WIDTH 32
`define GPIO_DATA_OUT_VALUE_BIT_MASK 32'hffffffff
`define GPIO_DATA_OUT_VALUE_BIT_OFFSET 0
`define GPIO_DATA_OUT_BYTE_WIDTH 4
`define GPIO_DATA_OUT_BYTE_SIZE 4
`define GPIO_DATA_OUT_BYTE_OFFSET 4'h4
`define GPIO_DATA_IN_VALUE_BIT_WIDTH 32
`define GPIO_DATA_IN_VALUE_BIT_MASK 32'hffffffff
`define GPIO_DATA_IN_VALUE_BIT_OFFSET 0
`define GPIO_DATA_IN_BYTE_WIDTH 4
`define GPIO_DATA_IN_BYTE_SIZE 4
`define GPIO_DATA_IN_BYTE_OFFSET 4'h8
`endif
